import { Workout, Exercise } from '@types'

const generateId = () => Math.random().toString(36).substr(2, 9)

export const getSampleWorkouts = (): Workout[] => {
  const workouts: Workout[] = [
    {
      id: generateId(),
      name: 'Quick Morning Cardio',
      difficulty: 'Beginner',
      type: 'Cardio',
      exercises: [
        {
          id: generateId(),
          name: 'Jumping Jacks',
          description: 'Jump with arms and legs spread',
          workDuration: 45,
          restDuration: 15,
          reps: 1,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'High Knees',
          description: 'Run in place with high knee lifts',
          workDuration: 45,
          restDuration: 15,
          reps: 1,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Butt Kicks',
          description: 'Run in place kicking heels to glutes',
          workDuration: 45,
          restDuration: 15,
          reps: 1,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Mountain Climbers',
          description: 'Plank position with alternating knee drives',
          workDuration: 45,
          restDuration: 15,
          reps: 1,
          sets: 3,
        },
      ],
    },
    {
      id: generateId(),
      name: 'Core Strength Builder',
      difficulty: 'Intermediate',
      type: 'Strength',
      exercises: [
        {
          id: generateId(),
          name: 'Plank',
          description: 'Hold a straight body position',
          workDuration: 60,
          restDuration: 30,
          reps: 1,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Crunches',
          description: 'Lift shoulders off ground using core',
          workDuration: 45,
          restDuration: 20,
          reps: 15,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Leg Raises',
          description: 'Raise legs while lying down',
          workDuration: 40,
          restDuration: 20,
          reps: 12,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Russian Twists',
          description: 'Twist torso side to side with weight',
          workDuration: 45,
          restDuration: 20,
          reps: 20,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Dead Bug',
          description: 'Lie down and extend opposite arm and leg',
          workDuration: 45,
          restDuration: 20,
          reps: 12,
          sets: 3,
        },
      ],
    },
    {
      id: generateId(),
      name: 'HIIT Blast',
      difficulty: 'Advanced',
      type: 'HIIT',
      exercises: [
        {
          id: generateId(),
          name: 'Burpees',
          description: 'Full body explosive movement',
          workDuration: 40,
          restDuration: 20,
          reps: 1,
          sets: 4,
        },
        {
          id: generateId(),
          name: 'Jump Squats',
          description: 'Explosive squat with vertical jump',
          workDuration: 40,
          restDuration: 20,
          reps: 1,
          sets: 4,
        },
        {
          id: generateId(),
          name: 'Push-up to Row',
          description: 'Push-up with dumbbell row alternating sides',
          workDuration: 40,
          restDuration: 20,
          reps: 1,
          sets: 4,
        },
        {
          id: generateId(),
          name: 'Sprint in Place',
          description: 'Run with maximum intensity',
          workDuration: 40,
          restDuration: 20,
          reps: 1,
          sets: 4,
        },
        {
          id: generateId(),
          name: 'Box Jumps',
          description: 'Jump onto and step down from elevated surface',
          workDuration: 40,
          restDuration: 20,
          reps: 1,
          sets: 4,
        },
      ],
    },
    {
      id: generateId(),
      name: 'Evening Stretch Flow',
      difficulty: 'Beginner',
      type: 'Cardio',
      exercises: [
        {
          id: generateId(),
          name: 'Neck Rolls',
          description: 'Slow circular motion of the neck',
          workDuration: 30,
          restDuration: 10,
          reps: 1,
          sets: 2,
        },
        {
          id: generateId(),
          name: 'Shoulder Stretch',
          description: 'Hold arms across chest and stretch',
          workDuration: 30,
          restDuration: 10,
          reps: 1,
          sets: 2,
        },
        {
          id: generateId(),
          name: 'Hip Flexor Stretch',
          description: 'Lunge position to stretch front hip',
          workDuration: 30,
          restDuration: 10,
          reps: 1,
          sets: 2,
        },
        {
          id: generateId(),
          name: 'Hamstring Hold',
          description: 'Forward fold to stretch back of legs',
          workDuration: 30,
          restDuration: 10,
          reps: 1,
          sets: 2,
        },
      ],
    },
    {
      id: generateId(),
      name: 'Upper Body Pump',
      difficulty: 'Intermediate',
      type: 'Strength',
      exercises: [
        {
          id: generateId(),
          name: 'Push-ups',
          description: 'Upper body pressing movement',
          workDuration: 45,
          restDuration: 20,
          reps: 12,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Tricep Dips',
          description: 'Bench dip or chair dip',
          workDuration: 45,
          restDuration: 20,
          reps: 10,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Pike Push-ups',
          description: 'Inverted push-up for shoulders',
          workDuration: 40,
          restDuration: 20,
          reps: 8,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Diamond Push-ups',
          description: 'Close grip push-up forming diamond',
          workDuration: 40,
          restDuration: 20,
          reps: 8,
          sets: 3,
        },
        {
          id: generateId(),
          name: 'Shoulder Taps',
          description: 'Plank position tapping shoulders',
          workDuration: 40,
          restDuration: 20,
          reps: 20,
          sets: 3,
        },
      ],
    },
    {
      id: generateId(),
      name: 'Tabata Finisher',
      difficulty: 'Advanced',
      type: 'HIIT',
      exercises: [
        {
          id: generateId(),
          name: 'Squat Jumps',
          description: 'Jump from squat position',
          workDuration: 20,
          restDuration: 10,
          reps: 1,
          sets: 8,
        },
        {
          id: generateId(),
          name: 'Push-ups',
          description: 'Upper body pressing movement',
          workDuration: 20,
          restDuration: 10,
          reps: 1,
          sets: 8,
        },
        {
          id: generateId(),
          name: 'Plank Jacks',
          description: 'Plank position with jumping feet',
          workDuration: 20,
          restDuration: 10,
          reps: 1,
          sets: 8,
        },
        {
          id: generateId(),
          name: 'Tuck Jumps',
          description: 'Jump bringing knees to chest',
          workDuration: 20,
          restDuration: 10,
          reps: 1,
          sets: 8,
        },
      ],
    },
  ]

  return workouts
}
